version: '3'
services:
  client:
    image: client
    ports:
    - 5000:5000
    networks: 
      - client-server-network
    depends_on:
      - server
    volumes_from:
      - server:ro
  server:
    image: server
    ports:
    - 8000:8000
    networks:
      - client-server-network
    volumes:
      - ./:/app/A1_P2

networks:
  client-server-network:
    name: client-server-network

